// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: location.proto

package sep3.project.protobuf;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string postCode = 2;</code>
   * @return The postCode.
   */
  java.lang.String getPostCode();
  /**
   * <code>string postCode = 2;</code>
   * @return The bytes for postCode.
   */
  com.google.protobuf.ByteString
      getPostCodeBytes();

  /**
   * <code>string country = 3;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 3;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string town = 4;</code>
   * @return The town.
   */
  java.lang.String getTown();
  /**
   * <code>string town = 4;</code>
   * @return The bytes for town.
   */
  com.google.protobuf.ByteString
      getTownBytes();
}
