// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin.proto

package sep3.project.protobuf;

public interface AdminUsernameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AdminUsername)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string username = 1;</code>
   * @return Whether the username field is set.
   */
  boolean hasUsername();
  /**
   * <code>optional string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
