// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ban.proto

package sep3.project.protobuf;

public interface BanDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BanData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string admin = 1;</code>
   * @return The admin.
   */
  java.lang.String getAdmin();
  /**
   * <code>string admin = 1;</code>
   * @return The bytes for admin.
   */
  com.google.protobuf.ByteString
      getAdminBytes();

  /**
   * <code>int64 postId = 2;</code>
   * @return The postId.
   */
  long getPostId();

  /**
   * <code>string reason = 3;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 3;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
