// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment.proto

package sep3.project.protobuf;

public interface CommentDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommentData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string body = 2;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 2;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>int64 ownerId = 3;</code>
   * @return The ownerId.
   */
  long getOwnerId();

  /**
   * <code>int64 postId = 4;</code>
   * @return The postId.
   */
  long getPostId();

  /**
   * <code>int64 createdOnMilliseconds = 5;</code>
   * @return The createdOnMilliseconds.
   */
  long getCreatedOnMilliseconds();
}
