// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: location.proto

package sep3.project.protobuf;

public final class Location {
  private Location() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CoordinatesData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CoordinatesData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocationData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocationData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddressData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddressData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocationId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocationId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016location.proto\"6\n\017CoordinatesData\022\020\n\010l" +
      "atitude\030\001 \001(\002\022\021\n\tlongitude\030\002 \001(\002\"u\n\014Loca" +
      "tionData\022\017\n\007address\030\001 \001(\t\022\020\n\010postCode\030\002 " +
      "\001(\t\022\017\n\007country\030\003 \001(\t\022\014\n\004town\030\004 \001(\t\022\020\n\010la" +
      "titude\030\005 \001(\002\022\021\n\tlongitude\030\006 \001(\002\"O\n\013Addre" +
      "ssData\022\017\n\007address\030\001 \001(\t\022\020\n\010postCode\030\002 \001(" +
      "\t\022\017\n\007country\030\003 \001(\t\022\014\n\004town\030\004 \001(\t\"\030\n\nLoca" +
      "tionId\022\n\n\002id\030\001 \001(\0052\264\001\n\017LocationService\022/" +
      "\n\016GetCoordinates\022\013.LocationId\032\020.Coordina" +
      "tesData\022\'\n\nGetAddress\022\013.LocationId\032\014.Add" +
      "ressData\022!\n\003Get\022\013.LocationId\032\r.LocationD" +
      "ata\022$\n\006Create\022\r.LocationData\032\013.LocationI" +
      "dB\031\n\025sep3.project.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CoordinatesData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CoordinatesData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CoordinatesData_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_LocationData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LocationData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocationData_descriptor,
        new java.lang.String[] { "Address", "PostCode", "Country", "Town", "Latitude", "Longitude", });
    internal_static_AddressData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AddressData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddressData_descriptor,
        new java.lang.String[] { "Address", "PostCode", "Country", "Town", });
    internal_static_LocationId_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LocationId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocationId_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
