// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: post.proto

package sep3.project.protobuf;

public final class PostOuterClass {
  private PostOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestCreatePost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestCreatePost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseCreatePost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseCreatePost_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\npost.proto\"F\n\021RequestCreatePost\022\r\n\005lik" +
      "es\030\001 \001(\005\022\r\n\005title\030\002 \001(\t\022\023\n\013description\030\003" +
      " \001(\t\"q\n\022ResponseCreatePost\022\n\n\002id\030\001 \001(\005\022\r" +
      "\n\005likes\030\002 \001(\005\022\r\n\005title\030\003 \001(\t\022\023\n\013descript" +
      "ion\030\004 \001(\t\022\034\n\024postedOnMilliseconds\030\005 \001(\0032" +
      "=\n\004Post\0225\n\nCreatePost\022\022.RequestCreatePos" +
      "t\032\023.ResponseCreatePostB\031\n\025sep3.project.p" +
      "rotobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RequestCreatePost_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestCreatePost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestCreatePost_descriptor,
        new java.lang.String[] { "Likes", "Title", "Description", });
    internal_static_ResponseCreatePost_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseCreatePost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseCreatePost_descriptor,
        new java.lang.String[] { "Id", "Likes", "Title", "Description", "PostedOnMilliseconds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
