// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: post.proto

package sep3.project.protobuf;

public final class Post {
  private Post() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestCreatePost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestCreatePost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseCreatePost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseCreatePost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PostData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestDeletePost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestDeletePost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyPost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyPost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestGetPost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestGetPost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseGetPost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseGetPost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestUpdatePost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestUpdatePost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseUpdatePost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseUpdatePost_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\npost.proto\"k\n\021RequestCreatePost\022\r\n\005tit" +
      "le\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\016\n\006userId\030" +
      "\003 \001(\003\022\016\n\006imgUrl\030\004 \001(\t\022\022\n\nlocationId\030\005 \001(" +
      "\005\" \n\022ResponseCreatePost\022\n\n\002id\030\001 \001(\003\"\233\001\n\010" +
      "PostData\022\n\n\002id\030\001 \001(\003\022\016\n\006userId\030\002 \001(\003\022\r\n\005" +
      "likes\030\003 \001(\005\022\r\n\005title\030\004 \001(\t\022\023\n\013descriptio" +
      "n\030\005 \001(\t\022\016\n\006imgUrl\030\006 \001(\t\022\022\n\nlocationId\030\007 " +
      "\001(\005\022\034\n\024postedOnMilliseconds\030\010 \001(\003\"\037\n\021Req" +
      "uestDeletePost\022\n\n\002id\030\001 \001(\003\"\013\n\tEmptyPost\"" +
      "f\n\016RequestGetPost\022\017\n\002id\030\001 \001(\003H\000\210\001\001\022\023\n\006us" +
      "erId\030\002 \001(\003H\001\210\001\001\022\022\n\005title\030\003 \001(\tH\002\210\001\001B\005\n\003_" +
      "idB\t\n\007_userIdB\010\n\006_title\"+\n\017ResponseGetPo" +
      "st\022\030\n\005posts\030\001 \003(\0132\t.PostData\"Q\n\021RequestU" +
      "pdatePost\022\n\n\002id\030\001 \001(\003\022\r\n\005title\030\002 \001(\t\022\023\n\013" +
      "description\030\003 \001(\t\022\014\n\004tags\030\004 \003(\t\" \n\022Respo" +
      "nseUpdatePost\022\n\n\002id\030\001 \001(\0032\327\001\n\013PostServic" +
      "e\0225\n\nCreatePost\022\022.RequestCreatePost\032\023.Re" +
      "sponseCreatePost\022,\n\007GetPost\022\017.RequestGet" +
      "Post\032\020.ResponseGetPost\022,\n\nDeletePost\022\022.R" +
      "equestDeletePost\032\n.EmptyPost\0225\n\nUpdatePo" +
      "st\022\022.RequestUpdatePost\032\023.ResponseUpdateP" +
      "ostB\031\n\025sep3.project.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RequestCreatePost_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestCreatePost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestCreatePost_descriptor,
        new java.lang.String[] { "Title", "Description", "UserId", "ImgUrl", "LocationId", });
    internal_static_ResponseCreatePost_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseCreatePost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseCreatePost_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_PostData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PostData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PostData_descriptor,
        new java.lang.String[] { "Id", "UserId", "Likes", "Title", "Description", "ImgUrl", "LocationId", "PostedOnMilliseconds", });
    internal_static_RequestDeletePost_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RequestDeletePost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestDeletePost_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_EmptyPost_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_EmptyPost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyPost_descriptor,
        new java.lang.String[] { });
    internal_static_RequestGetPost_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_RequestGetPost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestGetPost_descriptor,
        new java.lang.String[] { "Id", "UserId", "Title", "Id", "UserId", "Title", });
    internal_static_ResponseGetPost_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ResponseGetPost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseGetPost_descriptor,
        new java.lang.String[] { "Posts", });
    internal_static_RequestUpdatePost_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_RequestUpdatePost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestUpdatePost_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "Tags", });
    internal_static_ResponseUpdatePost_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ResponseUpdatePost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseUpdatePost_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
