// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package sep3.project.protobuf;

public final class Report {
  private Report() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestReportPost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestReportPost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseReportPost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseReportPost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestGetByIdReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestGetByIdReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseGetReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseGetReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReportData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReportData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014report.proto\"M\n\021RequestReportPost\022\026\n\016v" +
      "iolation_desc\030\001 \001(\t\022\017\n\007post_id\030\002 \001(\005\022\017\n\007" +
      "user_id\030\003 \001(\005\"\'\n\022ResponseReportPost\022\021\n\tr" +
      "eport_id\030\001 \001(\005\")\n\024RequestGetByIdReport\022\021" +
      "\n\treport_id\030\001 \001(\005\"`\n\021ResponseGetReport\022\021" +
      "\n\treport_id\030\001 \001(\005\022\026\n\016violation_desc\030\002 \001(" +
      "\t\022\017\n\007post_id\030\003 \001(\005\022\017\n\007user_id\030\004 \001(\005\"Y\n\nR" +
      "eportData\022\021\n\treport_id\030\001 \001(\005\022\026\n\016violatio" +
      "n_desc\030\002 \001(\t\022\017\n\007post_id\030\003 \001(\005\022\017\n\007user_id" +
      "\030\004 \001(\0052\202\001\n\rReportService\0225\n\nReportPost\022\022" +
      ".RequestReportPost\032\023.ResponseReportPost\022" +
      ":\n\rGetByIdReport\022\025.RequestGetByIdReport\032" +
      "\022.ResponseGetReportB\031\n\025sep3.project.prot" +
      "obufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RequestReportPost_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestReportPost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestReportPost_descriptor,
        new java.lang.String[] { "ViolationDesc", "PostId", "UserId", });
    internal_static_ResponseReportPost_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseReportPost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseReportPost_descriptor,
        new java.lang.String[] { "ReportId", });
    internal_static_RequestGetByIdReport_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RequestGetByIdReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestGetByIdReport_descriptor,
        new java.lang.String[] { "ReportId", });
    internal_static_ResponseGetReport_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ResponseGetReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseGetReport_descriptor,
        new java.lang.String[] { "ReportId", "ViolationDesc", "PostId", "UserId", });
    internal_static_ReportData_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ReportData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReportData_descriptor,
        new java.lang.String[] { "ReportId", "ViolationDesc", "PostId", "UserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
