// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package sep3.project.protobuf;

public interface RequestGetUsersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestGetUsers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string username = 1;</code>
   * @return Whether the username field is set.
   */
  boolean hasUsername();
  /**
   * <code>optional string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional int64 userid = 2;</code>
   * @return Whether the userid field is set.
   */
  boolean hasUserid();
  /**
   * <code>optional int64 userid = 2;</code>
   * @return The userid.
   */
  long getUserid();
}
