// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment.proto

package sep3.project.protobuf;

public interface RequestAssignCommentToParentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestAssignCommentToParent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>int64 parentId = 2;</code>
   * @return The parentId.
   */
  long getParentId();
}
