// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package sep3.project.protobuf;

public interface RequestGetLikesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestGetLikes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 postId = 1;</code>
   * @return The postId.
   */
  int getPostId();
}
