// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Like.proto

package sep3.project.protobuf;

public interface RequestIsPostLikedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestIsPostLiked)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 postId = 1;</code>
   * @return The postId.
   */
  long getPostId();

  /**
   * <code>int64 userId = 2;</code>
   * @return The userId.
   */
  long getUserId();
}
