// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: post.proto

package sep3.project.protobuf;

public interface RequestGetPostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestGetPost)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>optional int64 userId = 2;</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <code>optional int64 userId = 2;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>optional string title = 3;</code>
   * @return Whether the title field is set.
   */
  boolean hasTitle();
  /**
   * <code>optional string title = 3;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>optional string title = 3;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();
}
