// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment.proto

package sep3.project.protobuf;

public interface RequestDeleteCommentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestDeleteComment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 postId = 1;</code>
   * @return The postId.
   */
  long getPostId();
}
