// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tag.proto

package sep3.project.protobuf;

public interface RequestGetPostTagOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestGetPostTag)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 postId = 1;</code>
   * @return Whether the postId field is set.
   */
  boolean hasPostId();
  /**
   * <code>optional int64 postId = 1;</code>
   * @return The postId.
   */
  long getPostId();

  /**
   * <code>optional string tagContains = 2;</code>
   * @return Whether the tagContains field is set.
   */
  boolean hasTagContains();
  /**
   * <code>optional string tagContains = 2;</code>
   * @return The tagContains.
   */
  java.lang.String getTagContains();
  /**
   * <code>optional string tagContains = 2;</code>
   * @return The bytes for tagContains.
   */
  com.google.protobuf.ByteString
      getTagContainsBytes();
}
