// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tag.proto

package sep3.project.protobuf;

public interface RequestDeleteTagOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestDeleteTag)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 postId = 1;</code>
   * @return The postId.
   */
  long getPostId();
}
