// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Like.proto

package sep3.project.protobuf;

public interface ResponseCountLikesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseCountLikes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 likesNo = 1;</code>
   * @return The likesNo.
   */
  int getLikesNo();
}
