// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment.proto

package sep3.project.protobuf;

public interface ResponseCreateCommentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseCreateComment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
