// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: post.proto

package sep3.project.protobuf;

public interface ResponseCreatePostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseCreatePost)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
