// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package sep3.project.protobuf;

public interface ResponseCreateUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseCreateUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UserData userData = 1;</code>
   * @return Whether the userData field is set.
   */
  boolean hasUserData();
  /**
   * <code>.UserData userData = 1;</code>
   * @return The userData.
   */
  sep3.project.protobuf.UserData getUserData();
  /**
   * <code>.UserData userData = 1;</code>
   */
  sep3.project.protobuf.UserDataOrBuilder getUserDataOrBuilder();
}
