// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tag.proto

package sep3.project.protobuf;

public interface ResponseGetPostTagOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseGetPostTag)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PostTagData tags = 1;</code>
   */
  java.util.List<sep3.project.protobuf.PostTagData> 
      getTagsList();
  /**
   * <code>repeated .PostTagData tags = 1;</code>
   */
  sep3.project.protobuf.PostTagData getTags(int index);
  /**
   * <code>repeated .PostTagData tags = 1;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated .PostTagData tags = 1;</code>
   */
  java.util.List<? extends sep3.project.protobuf.PostTagDataOrBuilder> 
      getTagsOrBuilderList();
  /**
   * <code>repeated .PostTagData tags = 1;</code>
   */
  sep3.project.protobuf.PostTagDataOrBuilder getTagsOrBuilder(
      int index);
}
