// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package sep3.project.protobuf;

public interface ResponseLikePostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseLikePost)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 postId = 1;</code>
   * @return The postId.
   */
  int getPostId();

  /**
   * <code>int64 userId = 2;</code>
   * @return The userId.
   */
  long getUserId();
}
