// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package sep3.project.protobuf;

public interface ResponseGetReportsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseGetReports)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ReportData reports = 1;</code>
   */
  java.util.List<sep3.project.protobuf.ReportData> 
      getReportsList();
  /**
   * <code>repeated .ReportData reports = 1;</code>
   */
  sep3.project.protobuf.ReportData getReports(int index);
  /**
   * <code>repeated .ReportData reports = 1;</code>
   */
  int getReportsCount();
  /**
   * <code>repeated .ReportData reports = 1;</code>
   */
  java.util.List<? extends sep3.project.protobuf.ReportDataOrBuilder> 
      getReportsOrBuilderList();
  /**
   * <code>repeated .ReportData reports = 1;</code>
   */
  sep3.project.protobuf.ReportDataOrBuilder getReportsOrBuilder(
      int index);
}
