// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tag.proto

package sep3.project.protobuf;

public final class Tag {
  private Tag() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestGetPostTag_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestGetPostTag_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseGetPostTag_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseGetPostTag_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostTagData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PostTagData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestGetTagList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestGetTagList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseGetTagList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseGetTagList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TagListData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TagListData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ttag.proto\"]\n\021RequestGetPostTag\022\023\n\006post" +
      "Id\030\001 \001(\005H\000\210\001\001\022\030\n\013tagContains\030\002 \001(\tH\001\210\001\001B" +
      "\t\n\007_postIdB\016\n\014_tagContains\"0\n\022ResponseGe" +
      "tPostTag\022\032\n\004tags\030\001 \003(\0132\014.PostTagData\"W\n\013" +
      "PostTagData\022\023\n\006postId\030\001 \001(\005H\000\210\001\001\022\030\n\013tagC" +
      "ontains\030\002 \001(\tH\001\210\001\001B\t\n\007_postIdB\016\n\014_tagCon" +
      "tains\"=\n\021RequestGetTagList\022\030\n\013tagContain" +
      "s\030\001 \001(\tH\000\210\001\001B\016\n\014_tagContains\"0\n\022Response" +
      "GetTagList\022\032\n\004tags\030\001 \003(\0132\014.TagListData\"7" +
      "\n\013TagListData\022\030\n\013tagContains\030\001 \001(\tH\000\210\001\001B" +
      "\016\n\014_tagContains2z\n\nTagService\0225\n\nGetPost" +
      "Tag\022\022.RequestGetPostTag\032\023.ResponseGetPos" +
      "tTag\0225\n\nGetTagList\022\022.RequestGetTagList\032\023" +
      ".ResponseGetTagListB\031\n\025sep3.project.prot" +
      "obufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RequestGetPostTag_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestGetPostTag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestGetPostTag_descriptor,
        new java.lang.String[] { "PostId", "TagContains", "PostId", "TagContains", });
    internal_static_ResponseGetPostTag_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseGetPostTag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseGetPostTag_descriptor,
        new java.lang.String[] { "Tags", });
    internal_static_PostTagData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PostTagData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PostTagData_descriptor,
        new java.lang.String[] { "PostId", "TagContains", "PostId", "TagContains", });
    internal_static_RequestGetTagList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RequestGetTagList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestGetTagList_descriptor,
        new java.lang.String[] { "TagContains", "TagContains", });
    internal_static_ResponseGetTagList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ResponseGetTagList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseGetTagList_descriptor,
        new java.lang.String[] { "Tags", });
    internal_static_TagListData_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_TagListData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TagListData_descriptor,
        new java.lang.String[] { "TagContains", "TagContains", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
