// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tag.proto

package sep3.project.protobuf;

public interface TagListDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TagListData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tagContains = 1;</code>
   * @return The tagContains.
   */
  java.lang.String getTagContains();
  /**
   * <code>string tagContains = 1;</code>
   * @return The bytes for tagContains.
   */
  com.google.protobuf.ByteString
      getTagContainsBytes();
}
