// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package sep3.project.protobuf;

public interface UserEmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserEmpty)
    com.google.protobuf.MessageOrBuilder {
}
