// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package sep3.project.protobuf;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestCreateUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestCreateUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseLikePost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseLikePost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestLikePost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestLikePost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestGetUsers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestGetUsers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseGetUsers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseGetUsers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestGetLikes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestGetLikes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseGetLikes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseGetLikes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestCountLikes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestCountLikes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseCountLikes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseCountLikes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserEmpty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserEmpty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestUnLikePost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestUnLikePost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestIsPostLiked_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestIsPostLiked_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseIsPostLiked_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseIsPostLiked_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"\203\001\n\010UserData\022\n\n\002id\030\001 \001(\003\022\020\n" +
      "\010username\030\002 \001(\t\022\021\n\tfirstName\030\003 \001(\t\022\020\n\010la" +
      "stName\030\004 \001(\t\022\r\n\005email\030\005 \001(\t\022\020\n\010password\030" +
      "\006 \001(\t\022\023\n\013phoneNumber\030\007 \001(\t\"\200\001\n\021RequestCr" +
      "eateUser\022\020\n\010username\030\001 \001(\t\022\021\n\tfirstName\030" +
      "\002 \001(\t\022\020\n\010lastName\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\020" +
      "\n\010password\030\005 \001(\t\022\023\n\013phoneNumber\030\006 \001(\t\"2\n" +
      "\020ResponseLikePost\022\016\n\006postId\030\001 \001(\005\022\016\n\006use" +
      "rId\030\002 \001(\003\"1\n\017RequestLikePost\022\016\n\006postId\030\001" +
      " \001(\005\022\016\n\006userId\030\002 \001(\003\"U\n\017RequestGetUsers\022" +
      "\025\n\010username\030\001 \001(\tH\000\210\001\001\022\023\n\006userid\030\002 \001(\003H\001" +
      "\210\001\001B\013\n\t_usernameB\t\n\007_userid\"/\n\020ResponseG" +
      "etUsers\022\033\n\010userData\030\001 \003(\0132\t.UserData\"!\n\017" +
      "RequestGetLikes\022\016\n\006postId\030\001 \001(\005\"+\n\020Respo" +
      "nseGetLikes\022\027\n\004user\030\001 \003(\0132\t.UserData\"#\n\021" +
      "RequestCountLikes\022\016\n\006postId\030\001 \001(\005\"%\n\022Res" +
      "ponseCountLikes\022\017\n\007likesNo\030\001 \001(\005\"\013\n\tUser" +
      "Empty\"3\n\021RequestUnLikePost\022\016\n\006postId\030\001 \001" +
      "(\005\022\016\n\006userId\030\002 \001(\003\"4\n\022RequestIsPostLiked" +
      "\022\016\n\006postId\030\001 \001(\005\022\016\n\006userId\030\002 \001(\003\"&\n\023Resp" +
      "onseIsPostLiked\022\017\n\007isLiked\030\001 \001(\0102\354\002\n\013Use" +
      "rService\022+\n\nCreateUser\022\022.RequestCreateUs" +
      "er\032\t.UserData\022/\n\010LikePost\022\020.RequestLikeP" +
      "ost\032\021.ResponseLikePost\022,\n\nUnLikePost\022\022.R" +
      "equestUnLikePost\032\n.UserEmpty\0228\n\013IsPostLi" +
      "ked\022\023.RequestIsPostLiked\032\024.ResponseIsPos" +
      "tLiked\022/\n\010GetUsers\022\020.RequestGetUsers\032\021.R" +
      "esponseGetUsers\022/\n\010GetLikes\022\020.RequestGet" +
      "Likes\032\021.ResponseGetLikes\0225\n\nCountLikes\022\022" +
      ".RequestCountLikes\032\023.ResponseCountLikesB" +
      "\031\n\025sep3.project.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserData_descriptor,
        new java.lang.String[] { "Id", "Username", "FirstName", "LastName", "Email", "Password", "PhoneNumber", });
    internal_static_RequestCreateUser_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RequestCreateUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestCreateUser_descriptor,
        new java.lang.String[] { "Username", "FirstName", "LastName", "Email", "Password", "PhoneNumber", });
    internal_static_ResponseLikePost_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ResponseLikePost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseLikePost_descriptor,
        new java.lang.String[] { "PostId", "UserId", });
    internal_static_RequestLikePost_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RequestLikePost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestLikePost_descriptor,
        new java.lang.String[] { "PostId", "UserId", });
    internal_static_RequestGetUsers_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RequestGetUsers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestGetUsers_descriptor,
        new java.lang.String[] { "Username", "Userid", "Username", "Userid", });
    internal_static_ResponseGetUsers_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ResponseGetUsers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseGetUsers_descriptor,
        new java.lang.String[] { "UserData", });
    internal_static_RequestGetLikes_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_RequestGetLikes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestGetLikes_descriptor,
        new java.lang.String[] { "PostId", });
    internal_static_ResponseGetLikes_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ResponseGetLikes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseGetLikes_descriptor,
        new java.lang.String[] { "User", });
    internal_static_RequestCountLikes_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_RequestCountLikes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestCountLikes_descriptor,
        new java.lang.String[] { "PostId", });
    internal_static_ResponseCountLikes_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ResponseCountLikes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseCountLikes_descriptor,
        new java.lang.String[] { "LikesNo", });
    internal_static_UserEmpty_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_UserEmpty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserEmpty_descriptor,
        new java.lang.String[] { });
    internal_static_RequestUnLikePost_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_RequestUnLikePost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestUnLikePost_descriptor,
        new java.lang.String[] { "PostId", "UserId", });
    internal_static_RequestIsPostLiked_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_RequestIsPostLiked_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestIsPostLiked_descriptor,
        new java.lang.String[] { "PostId", "UserId", });
    internal_static_ResponseIsPostLiked_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ResponseIsPostLiked_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseIsPostLiked_descriptor,
        new java.lang.String[] { "IsLiked", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
